[project]
name = "penguins"
version = "0.1.0"
requires-python = ">=3.10"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.in"]}

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"
