channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=23.0.1
- pip:
  - mlflow==3.3.1
  - cloudpickle==3.1.1
  - numpy==2.2.6
  - pandas==2.3.2
  - pyarrow==21.0.0
  - scikit-learn==1.7.1
  - scipy==1.15.3
  - typing==3.7.4.3
name: mlflow-env
